name       : tracker
version    : 3.4.0
release    : 53
source     :
    - https://download.gnome.org/sources/tracker/3.4/tracker-3.4.0.tar.xz : b3b380c9571d7c7423b5f401e4a2f2d78de47143b035eb2c1281e2423c59218b
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : Semantic data storage
description: |
    Tracker is a semantic data storage for desktop and mobile devices. Tracker uses W3C standards for RDF ontologies using Nepomuk with SPARQL to query and update the data.
    Tracker is a central repository of user information, that provides two big benefits for the user; shared data between applications and information which is relational to other information (for example: mixing contacts with files, locations, activities and etc.).
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(icu-io)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libdevhelp-3.0)
    - pkgconfig(libmediaart-2.0)
    - pkgconfig(libnm)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(sqlite3)
    - pkgconfig(taglib)
    - pkgconfig(upower-glib)
    - asciidoc
    - lame-devel
    - vala
rundeps    :
    - devel :
        - libicu-devel
        - libsoup-devel
        - sqlite3-devel
setup      : |
    %meson_configure -Ddocs=false
build      : |
    %ninja_build -j1
install    : |
    %ninja_install
