name       : tracker
version    : 2.2.1
release    : 32
source     :
    - https://download.gnome.org/sources/tracker/2.2/tracker-2.2.1.tar.xz : 0ccef9e67440859119fa6cae230355c1b1b3485ac08122017c9499ad2dada2ff
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : Semantic data storage
description: |
    Tracker is a semantic data storage for desktop and mobile devices. Tracker uses W3C standards for RDF ontologies using Nepomuk with SPARQL to query and update the data.
    Tracker is a central repository of user information, that provides two big benefits for the user; shared data between applications and information which is relational to other information (for example: mixing contacts with files, locations, activities and etc.).
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(icu-io)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libdevhelp-3.0)
    - pkgconfig(libffi)
    - pkgconfig(libmediaart-2.0)
    - pkgconfig(libpcre)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(NetworkManager)
    - pkgconfig(sqlite3)
    - pkgconfig(taglib)
    - pkgconfig(upower-glib)
    - glibc-devel
    - gtk-doc
    - lame-devel
    - vala
setup      : |
    %meson_configure -Ddocs=true
build      : |
    %ninja_build
install    : |
    %ninja_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
